### ISSUE TITLE
No check if uploads/tx_seminars exists

### ISSUE THREAD

**Issue by AlexanderSchaper** [oliverklee/ext-seminars#1]
Hi,

today a got an error while I was adding an image to a seminar:

`1: The destination (/var/www/domain.tld/uploads/tx_seminars) or the source file (/var/www/domain.tld/fileadmin/path/to/file/filename.jpg) does not exist. (tx_seminars_seminars:2:image)`

The sourcefile was picked inside filewizard.

After checking the uploads folder the target folder tx_seminars is missing. 
I created it manually so the error does not occour anymore. 

Is there a check missing if the folder exists?

Best Regards

**Comment by oliverklee** [comment]
Hi, could you please test whether the folder will be automatically created if you uninstall the extension, delete (or rename) the folder, and then re-install the extension?

**Comment by oliverklee** [comment]
Here's the same bug in the old issue tracker: https://bugs.oliverklee.com/show_bug.cgi?id=5779

**Comment by AlexanderSchaper** [comment]
The folder is not created after reinstall.
