### ISSUE TITLE
Call to undefined method Tx_Seminars_Mapper_FrontEndUser::findByUserName()

### ISSUE THREAD

**Issue by synadmin** [oliverklee/ext-seminars#1219]
Hallo Herr Klee,

vielen Dank für die Info - sollte es wiedererwartend länger als 1 Std. dauern setzen Sie sich mit mir in Verbindung.

Der Fehler tritt auf, wenn ich das Anmeldeformular ausgefüllt habe und es absenden möchte. **ABER** nur wenn ich mehr als einen Sitz buchen möchte. (Ich habe die Zahl auf 4 begrenzt)

Hier die Daten die ich eingegeben habe:
[screencapture-typo3-p602631-anmeldung.pdf](https://github.com/oliverklee/ext-seminars/files/7497824/screencapture-typo3-p602631-anmeldung.pdf)

Sie können sich auch gern selbst anmelden und ein Seminar buchen mit 2 oder mehr Teilnehmern.

http://typo3.p602631.webspaceconfig.de/dd/de/veranstaltungen/veranstaltungsuebersicht

-----------------------------
Current TYPO3 Version	9.5.31
PHP	7.2.34	7.2
Mysql	5.7.18	5.0-5.7

1	A base library for...	rn_base		1.13.10	
2	MK Forms	mkforms		9.5.2	
3	Static Info Tables	static_info_tables	6.9.5	
4	One is Enough Library	oelib		3.6.3	
5	Front End User...	sr_feuser_register	7.0.5
6	Seminar Manager	seminars		3.4.0	
7	Grid Elements	gridelements		9.7.0	
8	Bootstrap Components	t3sbootstrap		4.4.5	
9	SASS compiler for TYPO3	ws_scss		1.1.15	
10	TYPO3 Console	typo3_console	5.8.6	

Testumgebung:
http://typo3.p602631.webspaceconfig.de/dd/de/veranstaltungen/veranstaltungsuebersicht

Fehlermeldung: Call to undefined method Tx_Seminars_Mapper_FrontEndUser::findByUserName()

Ich kann Ihnen auch einen Zugang zum Typo3-Backend senden.

Meine Rechnungsdaten:

Thomas Schmidt
syn|at|work - Büro für Gestaltung
Ahornallee 220
33330 Gütersloh
Fon +49 5241 - 211 54 84
Fax  +49 5241 - 211 54 85
E-Mail  ts@synatwork.de
Website: http://www.synatwork.de

Viele Grüße 
Thomas Schmidt

**Comment by oliverklee** [comment]
Already fixed by #1001 in V4.0.0. Closing.
