### ISSUE TITLE
Selectable categories with multiple domains

### ISSUE THREAD

**Issue by leofuehringer** [oliverklee/ext-seminars#122]
Hello,

I am using the seminars extension for multiple websites in one TYPO3 installation. After creating a seminar on the first website, all categories of the project are shown - also the ones from other websites, which is not what I want.
It would be nicer, if there was one folder, that contained the categories, organizers/hosts and locations and could further be browsed in recursively.
Or is there already a solution for this out there, that I am not seeing?

Thanks a lot in advance!
Cheers,

**Comment by oliverklee** [comment]
Marking as a feature request. @leofuehringer Would you be willing to provide a PR for this?

**Comment by leofuehringer** [comment]
So far, I have no experience with github and only few experience with the development of extension in general. I will try to figure out what kind of changes would be neccessary.

**Comment by leofuehringer** [comment]
See pullrequest #172
