### ISSUE TITLE
Fehler in Anmeldeform Step1 / Step2

### ISSUE THREAD

**Issue by synadmin** [oliverklee/ext-seminars#1228]
Hallo Herr Klee,

Sie hatten mir in #1219 geholfen indem ich meine Seminarsinstallation durch ein Update auf 4.0 upgedatet habe.

Jetzt ist leider erst jetzt aufgefallen das man im Anmeldeformular nicht mehr im 2. Schritt zurück auf den 1. Schritt gelangt.
Button (zurück) funktioniert nicht. 
Die Überprüfung ob ich die AGBs akzeptiere bringt mich auch nur in eine Schleife aus der ich nicht zurück komme.

Haben Sie eine Lösung?

System Information:
--
Current TYPO3 Version | 9.5.31
Target TYPO3 Version | 10.x
Total Languages | 2
Total Pages | 23
Total Domain | 1
PHP Version | 7.2.34

A base library for... | rn_base | 1.14.2
MK Forms | mkforms | 9.5.2
One is Enough Library | oelib | 3.6.3
Seminar Manager | seminars | 4.0.0

**Comment by oliverklee** [comment]
Closing as there has been no feedback for a long time.
