### ISSUE TITLE
Event time not shown

### ISSUE THREAD

**Issue by ULinn** [oliverklee/ext-seminars#124]
In list- and single-view there is only a "nbsp;" instead of the time, followed bei "Uhr" in a german installation. I think this was shown correctly before updateing to 2.0.1.
In backend, the time is set correctly.
Happens both with a single day events and events of more days.

**Comment by oliverklee** [comment]
Hi @ULinn, which TYPO3 version and which seminars version are you using?

Which steps are needed to reproduce the problem?

**Comment by ULinn** [comment]
Hi @oliverklee,

sorry for forgetting these infos:
Typo3: 7.6.27
Seminars: 1.4.1 

To reproduce:
Create an seminar with start- and end-time. 
Go to frontend-page with the seminarmanager plugin, single-view ("Vernstaltungs-Einzelansicht") (default settings).
Under the headline "Time" there is only an "&nbsp;Uhr"

**Comment by ULinn** [comment]
Now running under Typo3 7.6.29, same problem.

**Comment by oliverklee** [comment]
I've just tested this with the latest seminars master version in the latest TYPO3 7.6 and 8.7 and cannot reproduce this issue.

@ULinn As I don't support seminars 1.x anymore, could you please retest with the latest release seminars 2.0.1 and reopen this ticket if the issue still persists? Thanks!
