### ISSUE TITLE
Hooks implemented according to the manual raise an exception in Typo3 8.7.

### ISSUE THREAD

**Issue by djangones** [oliverklee/ext-seminars#125]
Everything worked as expected in Typo3 7.6. (and so did the implementation of `Tx_Seminars_Interface_Hook_EventListView`) but the following exception is raised in Typo3 8.7.15 now:

`#1301928334: The class Tx_Seminars_FrontEnd_DefaultController is used for the event list view hook, but does not implement the \Tx_Seminars_Interface_Hook_EventListView interface. `

The deprecation.log in Typo3 7.6. gives the following information:
`The persistent functionality of getUserObj(), prepending the class name with & is deprecated since TYPO3 CMS 7 and will be removed in TYPO3 CMS 8. To allow this functionality, implement  the \TYPO3\CMS\Core\SingletonInterface in the class "EXT:custom_ext/Classes/Hooks/ListView.php:&ListView" instead.`

**Comment by oliverklee** [comment]
Hi @djangones, thanks for the bug report!

Does using the hook as recommended by the error message solve the problem? Then I'll update the documentation accordingly. (And if you would like to help by providing a pull request, that would be awesome!)

**Comment by djangones** [comment]
Yes, together with a few other tiny adjustments to the hooking extension, this has led to the solution. I try to provide you with a pull request as soon as possible...
