### ISSUE TITLE
Seminar dependencies and requirements not loaded when opening an existing seminar record in the list view in Typo3 8.7.

### ISSUE THREAD

**Issue by djangones** [oliverklee/ext-seminars#126]
Typo3: 8.7.15
PHP: 7.0.28
seminars: 2.0.1

`1482250512: Mandatory TCA config setting "allowed" missing in field "dependencies" of table "tx_seminars_seminars"`

Adding the mandatory TCA setting does fix the exceptions but the requirements- and dependencies-lists still don't get loaded and there are a couple of the following PHP warnings:
`Warning: Invalid argument supplied for foreach() in [...]/typo3_sources/typo3_src-8.7.15/typo3/sysext/backend/Classes/Form/Element/SelectMultipleSideBySideElement.php on line 113`

**Comment by djangones** [comment]
I just realised that already in Typo3 7.6. there are no records (categories, dependencies, etc.) available for selection in the listboxes on the right side in the edit view of a seminar record.

Additionally the following extension manager configuration option has no effect:
`Use the page browser for selecting speakers, organizers etc. (instead of displaying a listbox or drop-down-list of records)
basic.usePageBrowser (boolesch) = true`

**Comment by djangones** [comment]
As soon as the EM option `basic.usePageBrowser` is set to `false` and after clearing the cache the selection of elements from the listbox works. Obviously only the selection via the wizard (`type = 'group'`) is affected...

**Comment by oliverklee** [comment]
I'll remove the basic.usePageBrowser option. Getting this option to work both ways both in 7.6 and 8.7 is too much of a hassle.
