### ISSUE TITLE
Duplicate attendance entries with IE and Edge

### ISSUE THREAD

**Issue by derhofbauer** [oliverklee/ext-seminars#129]
Sometimes two attendance entries are created, even if "Allows multiple registrations from the same person" is not checked. Entry uids are subsequent and two notification emails each are sent to the attendee and the organizer.

I tested this with multiple browsers on Linux and Windows but it only happens with Microsoft Edge and IE (used versions s. below) and even with those 2 browsers the problem does not occur with all tests. When the registration form is submitted by selecting the submit button using the tab key and hitting enter, everything works fine, when the button is clicked, two identical requests are sent by IE11 and Edge for some reason. In my opinion this is not a bug in your extension, but a bug in IE and Edge that should be handled in your extension. I guess it happens because the database entry is not set, when the second request checks whether a user is already attending or not.

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

Internet Explorer 11.112.17134.0

**Comment by oliverklee** [comment]
Hi @derhofbauer, thanks for the bug report! Would you be willing to create a pull request that fixes this issue?

**Comment by oliverklee** [comment]
Maybe we can catch the onclick event of the button, and if the button already is disabled (which should happen after the first click event), then discard the event?

**Comment by derhofbauer** [comment]
I added a pull request. The code works for me at least.
