### ISSUE TITLE
Setting `plugin.tx_seminars_pi1.limitFileDownloadToAttendees = 0` crashes plugin output

### ISSUE THREAD

**Issue by peerlight** [oliverklee/ext-seminars#1326]
When plugin.tx_seminars_pi1.limitFileDownloadToAttendees = 0 is set in TS then frontend only shows "htmlspecialchars() expects parameter 1 to be string, null given "

Log says
`...[CRITICAL] request="e3f6f469cf917" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: htmlspecialchars() expects parameter 1 to be string, null given | TypeError thrown in file /.../public/typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php in line 3060. Requested URL: ... - {"TYPO3_MODE":"FE","exception":{}}`

This seems to be caused by empty ("NULL") sys_file_metadata.title of some attached files.

How to prevent this technically 
- seminars: use $encodedFileName when $encodedTitle is empty to prevent empty title=""?
- TYPO3: assure fileed sys_file_metadata.title?

TYPO3 10.4.26
seminars 4.1.4
oelib 4.1.6

**Comment by oliverklee** [comment]
Thanks for the bug report, @peerlight! Would you be willing to provide a pull request with a fix?

**Comment by peerlight** [comment]
This occurs in a recently upgraded installation (TYPO3 9.5 -> 10.4, seminars 3.x -> 4.1.x) which was migrated to composer; PHP is 7.2

Sitepackage TS sets plugin.tx_seminars_pi1.limitFileDownloadToAttendees = 0 (overriding seminars default TS setting of 1)

Plugin setting limitFileDownloadToAttendees does not matter (on/off produces same result)

There must be at least one event having an attached file with empty sys_file_metadata.title in the result (means in the list or detail). 

fe display is correct when: 
- plugin.tx_seminars_pi1.limitFileDownloadToAttendees = 0 is commented or set to 1 in sitepackage
- list is shorter (problematic event out of date or count range)
- sys_file_metadata.title gets filled

What else do you need to know?

**Comment by oliverklee** [comment]
Thanks! I'll try to reproduce the problem.

Would you be willing to provide a PR with a fix? (That would speed things up.)

**Comment by oliverklee** [comment]
@peerlight Which view is affected? The default event list?

And is it required that a FE user is (not) logged in?

**Comment by peerlight** [comment]
> @peerlight Which view is affected? The default event list?
yes, seminars_pi1-Plugin with seminar_list plus single_view; did noch check others

> And is it required that a FE user is (not) logged in?
only checked without logged in user

**Comment by oliverklee** [comment]
Note: This is a bug in the core that was fixed in V11.

**Comment by oliverklee** [comment]
@peerlight I have just released version 4.1.5 with the fix.
