### ISSUE TITLE
v.3.4.2  Class 'GeneralUtility' not found

### ISSUE THREAD

**Issue by birgitberlin** [oliverklee/ext-seminars#1366]
use TYPO3\CMS\Core\Utility\GeneralUtility;
missing in 
Classes/FrontEnd/Editor.php

**Comment by oliverklee** [comment]
@birgitberlin Thanks for the bug report. Which version of seminars are you using?

**Comment by oliverklee** [comment]
Ah, I see, it's V3.4.2.
