### ISSUE TITLE
Add a "duplicate event" button to the BE module

### ISSUE THREAD

**Issue by peerlight** [oliverklee/ext-seminars#1384]
add a button to copy an event without duplicating registrations

- [x] repository method
- [x] label
- [x] controller action
  - [x] the action itself + tests
  - [x] duplicate
  - [x] redirect
  - [x] register action
- [x] find a nice icon: https://typo3.github.io/TYPO3.Icons/icons/actions/actions-duplicates.html
- [x] button + form
- [x] only display the button if the user has write access to event records
- [x] changelog
- [ ] DE translation
- [x] test in V10
- [x] test in V11
- [ ] update labels in the V10 testing distribution
- [ ] update labels in the V11 testing distribution
- [ ] update labels in the MRL installation

**Comment by oliverklee** [comment]
This can probably be resolved instead by dropping the event -> registration IRRE association.
