### ISSUE TITLE
CSV-download with error

### ISSUE THREAD

**Issue by infodry** [oliverklee/ext-seminars#140]
Downloading a csv with attendees causes an error.
But it's easy to fix: 
In TypoScript/setup.txt 
tx_seminars_pi2 {
    …
    10 {
        userFunc = \Tx_Seminars_Csv_CsvDownloader->main
    }
}

should be  userFunc = Tx_Seminars_Csv_CsvDownloader->main
without backslash.

Greetings

Steffen

**Comment by oliverklee** [comment]
Hi @infodry, thanks for the bug report! Would you be willing to provide a PR for this with the fix an and entry in the change log (newest on top)? :cookie:
