### ISSUE TITLE
Event headline on login page broken

### ISSUE THREAD

**Issue by ulrich4** [oliverklee/ext-seminars#1439]
Dear Oliver,

I found a problem with the get parameter tx_seminars_pi1[uid].

Please look in the controller OliverKlee\Seminars\FrontEnd\DefaultController
to the function  getLoginLink in line 593; 
`rawurlencode('tx_seminars_pi1[uid]') => $eventId,`
                        
In the class OliverKlee\Seminars\FrontEnd\EventHeadline 
the function render() works with the parameter called tx_seminars_pi1[showUid]:
`$eventId = (int)$this->piVars['showUid'];` //line 38

Greetings
Ulrich

**Comment by oliverklee** [comment]
Hi Ulrich, thank you for the bug report.

Which relevant content elements do you have on which page?

Which steps are required to reproduce the problem, what do you expect, and what happens instead?

**Comment by ulrich4** [comment]
Hi Oliver,
if a user choose an event from the list per link to register, he will come to the login page. On this page should appear the "Veranstaltungsüberschrift" [event_headline] of the selected event.
Due to the wrong term of the parameter the function render() (class OliverKlee\Seminars\FrontEnd\EventHeadline) doesn't get a value to find the selected recordset.
`$eventId = (int)$this->piVars['showUid'];`

The function returns an empty value:
```
        if ($eventId <= 0) {
            return '';
        }

```

previously (seminars 3.3.3):
`$eventId = (int)$this->piVars['uid'];`
//line 43

**Comment by oliverklee** [comment]
Hi Ulrich, having a seminars content element (like the event headline) on the login page is not supported (and will probably never be). The intention of the GET parameters in the login page URL is for redirection.

If you have an event headline element on the registration page or the thank-you page, and either of those is broken, please feel free to open a new issue. Thanks!

**Comment by oliverklee** [comment]
Reopening. We should get this to work.

**Comment by oliverklee** [comment]
I'll drop the event headline in seminars 5.0. So this is not worth fixing. Closing.
