### ISSUE TITLE
Add rel="nofollow" to sorting links in list view

### ISSUE THREAD

**Issue by ste101** [oliverklee/ext-seminars#145]
Search engines are following the sortings links in list view.
Please add the parameter ```rel="nofollow"``` to the link.

**Comment by oliverklee** [comment]
The pagination comes from `AbstractPlugin::pi_list_browseresults`:

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/Plugin/AbstractPlugin.php#L519

So as long as seminars is using the `AbstractPlugin` pagination, it cannot add any link attributes (as far as I can see). I propose you create a change request for the TYPO3 Core to add these attributes.
