### ISSUE TITLE
[BUG] Terms_2 are not displayed in the registration form

### ISSUE THREAD

**Issue by leofuehringer** [oliverklee/ext-seminars#189]
The terms_2 are not be displayed in the registration form even though plugin.tx_seminars_pi1.showRegistrationFields contains 'terms_2' 

I will try to fix this too in an PR.

**Comment by leofuehringer** [comment]
I retest it, when #188 ist solved...

**Comment by oliverklee** [comment]
Fixed in the rewritten registration form. Closing.
