### ISSUE TITLE
Question: Error after updating another Extension via Extension Manager

### ISSUE THREAD

**Issue by webdev2027** [oliverklee/ext-seminars#197]
Hi Oliver. Today, I've updated the crawler-extension and after it, there's an error with Ext.seminars?!?
How can I fix this, at the moment I can't check my Extension Manager anymore:
`class.ext_update.php of extension "seminars" did not declare ext_update class` see also screenshot

I have deactivate `crawler` but that wasn't the problem, I think?!
Do you have an idea?

I'm using still the old `TYPO3 7.6`with PHP7.0 and the latest Seminar-Extensions, all installed via Extension Manager . NO COMPOSER.
`Seminars` ist still running and it works, but I haven't access to the EM anymore.

![seminars](https://user-images.githubusercontent.com/5501876/51910212-d37e0f80-23ce-11e9-9cba-8ded7eb8e9da.png)

**Comment by oliverklee** [comment]
Hi @webdev2027, could you please have a look at that file on your installation and check whether it actually does not contain the class?

And are you using the seminars extension from TER or via Composer?

**Comment by oliverklee** [comment]
That's good to hear. Thanks for reporting back! Closing.
