### ISSUE TITLE
Image field for Speakers

### ISSUE THREAD

**Issue by sevensix** [oliverklee/ext-seminars#209]
We should have an image for the speakers out of the box. i could add this by changing the extension, but that is not good for updating the ext.. Is it possible to extend the seminars with an own extension like other extensions can be?

**Comment by oliverklee** [comment]
I'd like to have an image field (FAL-based) for speakers, and I think this feature makes sense to have in the official version of the extenion.

Would you be willing to create a PR for adding this field?

**Comment by oliverklee** [comment]
Done with 1cfb2dfd2d71277756f68ca5d63708f4750d168a and 4ddc22ec232c72521a92134ec22a14f1c3a020be.
