### ISSUE TITLE
Timeslots: places shown several times

### ISSUE THREAD

**Issue by ULinn** [oliverklee/ext-seminars#212]
If there are i.e. 6 timeslots with the same place, the places are shown in the timeslot-tablel together with date and time - perfec! 
But additionally the place is shown 6 times (below the description) - what makes no sense for me.

**Comment by oliverklee** [comment]
Hi @ULinn, thanks for the bug report. Could you please open a separate issue for the additional paragraph so we have on bug per issue? Thanks!

**Comment by ULinn** [comment]
Done. Shall I edit this report an delete the paragraph stuff?

**Comment by oliverklee** [comment]
> Done. Shall I edit this report an delete the paragraph stuff?

Thanks. I've already edited the issue description for you.

**Comment by oliverklee** [comment]
@ULinn It might be that the DataHandler hook that copies the places from the timeslots might create duplicate entries. Could you please check in the DB whether there are multiple identical entries in `tx_seminars_seminars_place_mm` (i.e., same `uid_local` and `uid_foreign`)? Thanks!
