### ISSUE TITLE
Two empty paragraphs in places / timeslots

### ISSUE THREAD

**Issue by ULinn** [oliverklee/ext-seminars#213]
When there are timeslots in detail view, after each place are two empty paragraphs with a nbsp:
`<dt>Testplace</dt> <dd>Teststreet, Testtown<p>&nbsp;</p> <p>&nbsp;</p></dd>`

**Comment by oliverklee** [comment]
Hi @ULinn, thanks for the bug report! Would you be willing to create a pull request for this?
