### ISSUE TITLE
TYPO3 9.5.X

### ISSUE THREAD

**Issue by HARZwerk** [oliverklee/ext-seminars#215]
Hi Oliver,

is there a roadmap for typo3 9.5.X and PHP 7.3 ?
and will it be possible to install seminars via composer?

BR, Ben

**Comment by oliverklee** [comment]
Yes, compatibility with TYPO3 9LTS and PHP 7.3 is planned. Currently, a crowdfunding campaign for this is running. Would you be willing to contribute? https://coders.care/for/crowdfunding/seminars/

The extension should already work fine with Composer. If you encounter any issues with this, please report them here.
