### ISSUE TITLE
Update call to ->IMAGE

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#24]
Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::IMAGE() 

Error thrown in file
typo3conf/ext/seminars/Classes/FrontEnd/CategoryList.php in line 186.

Error thrown in file
typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php in line 2057.

Needed replacements:
$myImage = $this->cObj->IMAGE($ImgConf);

with

$myImage = $this->cObj->cObjGetSingle('IMAGE', $ImgConf);

typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php

Line 2057:

replace
$image = $this->cObj->IMAGE($imageConfiguration);
width
$image = $this->cObj->cObjGetSingle('IMAGE', $imageConfiguration);

typo3conf/ext/seminars/Classes/FrontEnd/CategoryList.php

line: 186

replace
$imageWithoutClass = $this->cObj->IMAGE(
with
$imageWithoutClass = $this->cObj->cObjGetSingle('IMAGE',

**Comment by enilee** [comment]
and for createImageForSingleView

typo3conf/ext/seminars/Classes/OldModel/Event.php
line: 4556

replace:  
`$imageWithTag = $this->cObj->IMAGE($imageConfiguration);`
with
`$imageWithTag = $this->cObj->cObjGetSingle('IMAGE', $imageConfiguration);`


And in typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php

in the function part: `private function createCategoryIcon(array $iconData)`...

replace
`return $this->cObj->IMAGE(`
width
`return $this->cObj->cObjGetSingle('IMAGE',
`
