### ISSUE TITLE
Image not displayed in list view

### ISSUE THREAD

**Issue by tui15** [oliverklee/ext-seminars#2433]
The seminar list view does not display the seminar image
FrontEnd.html
`<img src="" alt="seminar" title="seminar" width="0" height="0">`

**Comment by oliverklee** [comment]
@tui15 Which TYPO3 version and which seminars version are you using?

And are you using the HTML template provided with the extension, or have you modified it?

**Comment by tui15** [comment]
Typo3 version 11
I didn't the HTML template modified

**Comment by oliverklee** [comment]
And which seminars version are you using?

**Comment by tui15** [comment]
Typo3 11.5.25 and Seminars V5.1.0

**Comment by tui15** [comment]
any idea?

**Comment by oliverklee** [comment]
No, I haven't had time to try to reproduce the problem yet.

A PR to fix this would be highly welcome.
