### ISSUE TITLE
missing templateFile error

### ISSUE THREAD

**Issue by itx-stefanie-doell** [oliverklee/ext-seminars#2440]
Hi,
thank you for your extension. Unfortunately I can't use it, because as soon as I place a plugin on the page, I get following error:

PHP Warning: Undefined array key "templateFile" in /var/www/html/public/typo3/sysext/frontend/Classes/Plugin/AbstractPlugin.php line 1425

I'm using your current version with typo3 11.5.14 and php 8.1

The error seems to be the result of removing the templateFile variable in your latest changes.

Thanks a lot.

**Comment by oliverklee** [comment]
Hi, do you have a stacktrace?

And which seminars plugin variant are you using? The list view? Or does this with any plugin (even non-seminars) happen?

**Comment by oliverklee** [comment]
Closing as there has been no feedback with more information for some months now.
