### ISSUE TITLE
Update the allowed maximum image size in TCA

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#25]
1: Filesize (301 Ki) of file 'fileadmin/images/kurse/fuhrparkdisposition/teaserimage-quadrat.jpg' exceeds limit (256 Ki). (tx_seminars_categories:2:icon)

**Comment by enilee** [comment]
My Fix is:
1. Add file to your Ext: typo3conf/ext/YOUR_EXTENSION/Configuration/TCA/Overrides/tx_seminars_categories.php

2. Add:
`$GLOBALS['TCA']['tx_seminars_categories']['columns']['icon']['config']['max_size'] = 2048;`

But:
if i deinstalled the seminars extension, TYPO3 give Error:

**Uncaught TYPO3 Exception**
#1482394401: Missing "type" in TCA of field "['tx_seminars_categories']['icon']['config']". (More information)

**UnexpectedValueException thrown in file** /typo3_src/typo3/sysext/core/Classes/Migrations/TcaMigration.php in line 116.


Which spelling is correct?
