### ISSUE TITLE
Automatically set the HTML `title` for the event single view

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#2517]
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Seo/PageTitleApi.html
https://www.andrerinas.de/tutorials/typo3-einen-pagetitleprovider-fuer-eigene-extension-erstellen.html

**Comment by mentronic** [comment]
Ja, <title> Detailansicht - IfHE: Institut für klinische Hypnose und Ego-State-Therapie</title> ist nicht gut
