### ISSUE TITLE
not more than 99 images with the same file name possible (image in event item)

### ISSUE THREAD

**Issue by enilee** [oliverklee/ext-seminars#26]
Theimage in event item:

not more than 99 images with the same file name possible

![image](https://user-images.githubusercontent.com/17785409/37979971-3c9dc88e-31ea-11e8-8a36-6f91c1cca78d.png)

**Comment by oliverklee** [comment]
This probably is a Core issue with automatic file names. Would you be willing to investigate this further?

**Comment by enilee** [comment]
At the moment I have no time. For that reason, I will not be able to care.
If I should find a solution, I will of course publish it.

**Comment by oliverklee** [comment]
It looks like this cannot be fixed without converting the images to FAL. Closing.
