### ISSUE TITLE
Description entry in the categories edit popup is missing after updating the seminars-extension

### ISSUE THREAD

**Issue by ovi1337** [oliverklee/ext-seminars#30]
I've upgraded the Typo3 and also the seminars extension. So far all is working well, but now i'm missing the description field in the categories editor popup:
This is the form of the old version (0.9.3)
![image](https://user-images.githubusercontent.com/9908262/38601033-9234eb4c-3d66-11e8-875b-9733f6c426b7.png)
 
![image](https://user-images.githubusercontent.com/9908262/38600916-24da6540-3d66-11e8-9fcd-787dc6922e50.png)

And this is the layout in the current version:
![image](https://user-images.githubusercontent.com/9908262/38603826-f8b226c0-3d6e-11e8-964f-a7270281c1ad.png)

![image](https://user-images.githubusercontent.com/9908262/38603845-065e84b2-3d6f-11e8-9904-c35f40859585.png)

Can you tell me what's wrong here and how it's possible to show the description field again please?

Thank you for your help!

**Comment by oliverklee** [comment]
@ovi1337 Do you see the description field if you create the category record directly from the list module?

**Comment by oliverklee** [comment]
@ovi1337 And which versions of seminars and TYPO3 are you using?

**Comment by ovi1337** [comment]
@oliverklee thank you for your quick response. It's Typo3 version 7.6.23 with seminars 1.4.1
No i also don't see it for new categories (if you mean this):
![image](https://user-images.githubusercontent.com/9908262/38617414-45da16ba-3d97-11e8-929a-0c6172adcea2.png)

![image](https://user-images.githubusercontent.com/9908262/38617383-276c6d0e-3d97-11e8-9582-1ae2a9ad2abb.png)

**Comment by oliverklee** [comment]
seminars 0.9.3 did not have a description field for categories:

https://github.com/oliverklee/ext-seminars/blob/version_0_9_x/ext_tables.sql#L723

I guess that your copy of seminars 0.9.3 was modified compared to the official release.
