### ISSUE TITLE
HTML E-mail Template not allow html

### ISSUE THREAD

**Issue by enilee** [oliverklee/ext-seminars#31]
Hello,
I´ve tested with and without <pre> Tags html in the email template, but in the email show the html Tags in plain text.

![image](https://user-images.githubusercontent.com/17785409/38626196-5c3c42ec-3dac-11e8-89b1-be90bf306083.png)

If i set the option in user profile:
![image](https://user-images.githubusercontent.com/17785409/38626293-846686c4-3dac-11e8-9719-3ee900fab62a.png)

its the same plain text.

And i sets global constant for:
plugin.tx_srfeuserregister_pi1. enableHTMLMail = 1

Is there another option I can set?

And i have one general question..
what's the difference between
plugin.tx_seminars {
and
plugin.tx_seminars_pi1 {?

Some configurations will not work unless they are configured under plugin.tx_seminars.

**Comment by oliverklee** [comment]
Please have a look in the extension settings in the EM. There the email format is configured.

`plugin.tx_seminars_pi1` is for settings that are FE-specific, whereas `plugin.tx_seminars` is for settings that are not FE-specific.

@enilee In the future, please don't use the issue tracker for posting questions. The issue tracker is for tracking bugs, features etc. For questions, please use a forum or the seminars newsgroup. I can also provide paid personal support via email.

**Comment by enilee** [comment]
Thank you oliver, i think that was a bug (no html in email) sorry!
