### ISSUE TITLE
nimut/testing_framework spills databases

### ISSUE THREAD

**Issue by mk-mxp** [oliverklee/ext-seminars#310]
This is not a problem when running the tests on Travis CI or another throw-away DB service, but for testing using a non-disposible MySQL instance (especially with shared instances).

A) The DB-user used for testing requires the right to create databases and self-grant all rights to it. By this, the user is root-like. This is inacceptible in shared DB instances and a risk to any other data stored in any DB on that instance.

B) For each test using the DB nimut creates a new DB copy with a random suffix:
```
mysql> show databases;
+----------------------+
| Database             |
+----------------------+
| information_schema   |
| mysql                |
| performance_schema   |
| typo3                |
| typo3_ft1d226aa      |
| typo3_ft53009df      |
| typo3_ft7054112      |
| typo3_ft9def141      |
| typo3_fta832130      |
| typo3_ftb9be75b      |
| typo3_ftc3170a5      |
| typo3_ftc799e14      |
| typo3_ftdcc4980      |
+----------------------+
```

And it never cleans up afterwards. Using random names makes it very annoying to cleanup manually.

I am not sure if this is caused by something related to seminars tests (the new functional ones) or unsolvable with nimut at all.

**Comment by oliverklee** [comment]
This is not an issue of seminars, but of `nimut/testing-framework`. Please report the issue there.

(I usually clean up the test databases manually. But maybe the TF can provide a console script to clean up all databases with the given prefix.)

**Comment by oliverklee** [comment]
(The prefix is the DB name given via the environment variable (e.g., 'typo3`) and then `_tf' .)

**Comment by oliverklee** [comment]
Correction: Only `_tf` seems to be the part added by `nimut/testing-framework` AFAICT.
