### ISSUE TITLE
Wrong times in iCal attachments

### ISSUE THREAD

**Issue by webdev2027** [oliverklee/ext-seminars#32]
Hi Oli.

There's a *.msg-file as an attachment (iCal or Outlook Cal ?!?) in the 'Thankyou-Mail' after booking a new seminar. The text is right, f.e. 'Course A at 04/11/18 - 09:00 - 16:00' , but the *.msg file has the wrong time, in my case +2 hours (11:00 - 18:00). The day and place is correct.

My server time is for germany (Europe/Berlin, GMT +02:00). I think this are the +2 hours, isn't it? What can I do? It would be helpful, to delete the attachment via typoscript. I don' t need the iCal-file for my participant ..?

I use `TYPO3 7.6.24` with `PHP5.5` and `seminars 1.4.1` (latest). I've read in your manual after my email to you, it's better to report bugs via github. Here it is .. ;)

**Comment by oliverklee** [comment]
@webdev2027 Would you willing to debug this further?

This is the corresponding line that creates the start date/time information in the iCal attachment:
https://github.com/oliverklee/ext-seminars/blob/master/Classes/Service/RegistrationManager.php#L896

This is the corresponding standard:
https://tools.ietf.org/html/rfc5546

A starting point would be to check whether the UNIX timestamp of the event (which does not have any time zone information) is correct: https://www.unixtimestamp.com/

**Comment by oliverklee** [comment]
My guess is that this is has to do with time zones (which is a really nasty topic).

**Comment by webdev2027** [comment]
Hi Oliver. I'm not a Backend-Developer, so I can't debug this - sorry. Would you add a checkbox, maybe in `constants.ts`, f.e. 'Send iCal-file in ThankYou-Mail as an attachment -> Yes/No'? So, If someone has problems with timezones, you'll can deavtivate this behaviour?! What do you think?

**Comment by oliverklee** [comment]
> Would you add a checkbox, maybe in constants.ts, f.e. 'Send iCal-file in ThankYou-Mail as an attachment -> Yes/No'? So, If someone has problems with timezones, you'll can deavtivate this behaviour?

No, I'd like to fix this bug instead.

**Comment by oliverklee** [comment]
@webdev2027 Could you please post the text contents of the iCal attachment and the values of the  `begin_date ` and `end_date` fields (UNIX timestamps, integers) of the corresponding event record?

**Comment by webdev2027** [comment]
@oliverklee I've sent you an e-mail yesterday. The iCal-file was attached, subject '.. iCal Attachment'. I can only send the remaining data on Monday ... maybe my e-mail will help you enough. Thanks.

**Comment by oliverklee** [comment]
This are the contents of the iCal attachment:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Zarafa//7.1.11-46050//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
TRANSP:OPAQUE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
CREATED:20180403T073146Z
LAST-MODIFIED:20180326T094136Z
DTSTAMP:20180326T094136Z
DTSTART:20180607T090000Z
DTEND:20180607T160000Z
SUMMARY:Aus der Praxis für die Praxis
LOCATION:Erzbischöfliches Ordinariat München\, Kapellenstr. 4\, 
 Kapellenstr. 4
CLASS:PUBLIC
UID:event/101/5ab8bfe48b75c2.37391331
X-MICROSOFT-CDO-OWNER-CRITICAL-CHANGE:20180403T073146Z
X-MICROSOFT-CDO-ATTENDEE-CRITICAL-CHANGE:20180403T073146Z
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:-1
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
END:VEVENT
END:VCALENDAR
```

**Comment by webdev2027** [comment]
looks right? `DTSTART:20180607T090000Z`and `DTEND:20180607T160000Z`
But the time which was shown was `11:00` and `18:00`, if you'll click the Outlook-file?!?

**Comment by oliverklee** [comment]
Google matches so far:
http://www.codepal.co.uk/show/ICS_incorrect_file_times_and_time_zone_problems_in_Outlook_calendars
https://icalevents.com/2613-what-every-developer-ought-to-know-about-timezones-wrt-calendar-files/
https://blog.philippklaus.de/2015/09/fixing-time-offsets-in-icalendar-ics-files

**Comment by oliverklee** [comment]
https://stackoverflow.com/questions/42919630/whats-vtimezone-used-for-in-icalendar-why-not-just-utc-time

**Comment by webdev2027** [comment]
...  "_Wanting to add a iCalendar (.ics) file to your calendar can become a nightmare if the times are incorrectly stated for a different time zones ..._"
That's my problem in fact. The iCal-Attachment leads to confusion in my (or other) case.

Is this a problem to set the timezone in the iCal-file? Do you have a solution?

Quick Fix is still a constant variable `YES attach iCal in Mail`or `NO`. The problem is currently acute, since all specified times are wrong. So you'll can work on the timezone-problem for 'seminars 2.0 (TYPO3 8.7)'. What do you think?

**Comment by webdev2027** [comment]
@oliverklee thanks for your help. Today I've changed the file `RegistrationManager.php`
This is my new ICS-File (iCal) output:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:TYPO3 CMS
METHOD:PUBLISH
BEGIN:VEVENT
UID:event/122/5ad5ca2d92adf0.22007810
DTSTAMP;TZID=/Europe/Berlin:20180417T121923
SUMMARY:### TEST THEMA FÜR ADMINS ###
DESCRIPTION:Untertitel Test
DTSTART;TZID=/Europe/Berlin:20180801T100000
DTEND;TZID=/Europe/Berlin:20180801T180000
LOCATION:Landvolkshochschule, Street 2
ORGANIZER;CN="Administrator":mailto:extern@domain.de
END:VEVENT
END:VCALENDAR
```

But beware! Before changing, I've made a new course with new data (e.g. admin stuff see ical). After registration I got the mail with the correct times in text and iCal. So I haven't the timezone problem on my computer. If my changes will be correct, we have to wait some other users will still have the problem.
