### ISSUE TITLE
seminars backend module: Download CSV file failed - no download -  frame reloaded

### ISSUE THREAD

**Issue by enilee** [oliverklee/ext-seminars#35]
Hello,

TYPO3 8.7.10
Seminars 1.4.1 (pre/8-compatibility)

---

If the CSV button is clicked in the backend module, no CSV file is downloaded, the frame is reloaded and nothing happens.

I understood the description as a CSV file is saved.

https://docs.typo3.org/typo3cms/extensions/seminars/DE/AnmeldungenVerwalten/BezahlungErfolgt/Index.html?highlight=csv#csv-export-of-events

---

![image](https://user-images.githubusercontent.com/17785409/38856701-73360c4c-4227-11e8-8bc3-d59c10e4e92c.png)

---

![image](https://user-images.githubusercontent.com/17785409/38856721-83f546a6-4227-11e8-8a97-4bb9e16dda99.png)

**Comment by oliverklee** [comment]
Hi @enilee, thanks for the bug report.

Do you get any errors on the browser JavaScript console? And could you please check the network tab of the browser dev tools for the request sent. Are there any errors in the HTTP response headers or the response content?

**Comment by enilee** [comment]
If i clicked, a error occurs:

![image](https://user-images.githubusercontent.com/17785409/38914448-ad580106-42df-11e8-8468-a20f1f06c76c.png)

---

In Network tab:

![image](https://user-images.githubusercontent.com/17785409/38914634-741f42b8-42e0-11e8-89c4-a7c730a5a95b.png)

**Comment by oliverklee** [comment]
I cannot reproduce this on my installation. @enilee My guess is that there is something special about your installation that causes the JavaScript errors, the problem with the CSV export and with the double content in the BE module. Could you please retest with a fresh TYPO3 installation (e.g., using https://github.com/helhum/TYPO3-Distribution), and then reopen the corresponding tickets if the problem still persists? Thanks!

**Comment by oliverklee** [comment]
Hi @enilee, I still cannot reproduce this problem on my machine. However, I've just removed all `echo` statements from the BE module code. Could you please retest with the current master whether this resolves this problem for you, and then report back here? Thanks!
