### ISSUE TITLE
Return value of `SingleEvent::getVenues()` is null

### ISSUE THREAD

**Issue by wegewerk-mdt** [oliverklee/ext-seminars#3565]
when sending emails after successful registration in RegistrationManager::notifyAttendee an Exception is thrown

`Return value of OliverKlee\Seminars\Domain\Model\Event\SingleEvent::getVenues() must be an instance of TYPO3\CMS\Extbase\Persistence\ObjectStorage, null returned`

And the function SingleEvent::setVenues() is never called?

**Comment by oliverklee** [comment]
Hi @wegewerk-mdt, which versions of TYPO3, seminars and oelib are you using?

**Comment by oliverklee** [comment]
And is this with or without any XCLASSes?

**Comment by wegewerk-mdt** [comment]
oliverklee/seminars v5.7.0
oliverklee/oelib 6.0.0
TYPO3 11.5.39

we XCLASSed \OliverKlee\Seminars\OldModel\LegacyEvent and \OliverKlee\Seminars\OldModel\LegacyRegistration

**Comment by oliverklee** [comment]
@wegewerk-mdt Does the event with which this occur have any related venues?

And if not, does the same problem also occur for you if the event has any venues?

**Comment by oliverklee** [comment]
I cannot reproduce this with the latest seminars 5.x branch (basically a 5.7.0) on the latest TYPO3 10LTS, and also not with the latest `main` on the latest TYPO3 11LTS, neither with an event withing venues nor with an event with 1 venue.

**Comment by oliverklee** [comment]
@wegewerk-mdt And could you please try these things and check whether they make any difference?

1. clear all TYPO3 caches (either using `typo3(cms) cache:flush` or the BE)
2. temporarily disable all XCLASSes for seminars
3. temporarily disable all Composer patches for seminars

**Comment by wegewerk-mdt** [comment]
I tested in a fresh TYPO3 v11 installation and cannot reproduce the error there.
Will test in my modified instance (DGE)

**Comment by oliverklee** [comment]
Thank you for the quick feedback! :pray:
