### ISSUE TITLE
HTML whitespace tags are being removed from Seminar description on save

### ISSUE THREAD

**Issue by sigma67** [oliverklee/ext-seminars#37]
When editing the description of a seminar in the backend, the HTML whitespace fields (e.g. \<br> tags or \<p> tags) are being removed and not stored in the database field 'description' of table 'tx_seminars_seminars'. Is this intended behavior? It seems counterintuitive that one linebreaks are possible in the backend but they are not being stored in the database.

I'm using version 1.3.0 on Typo3 7.6.

**Comment by oliverklee** [comment]
Hi @sigma67, thanks for the bug report!

This behavior is not intended.

Could you please test whether the same problem occurs with normal text content elements? If that is the case, then this is a general bug in TYPO3 (or a RTE configuration problem). If that is not the case, this is a configuration problem of the seminars RTE fields (and a PR to fix this will be very welcome.)

**Comment by oliverklee** [comment]
Oh, and just to be sure: Could you also please test with the latest seminars version 1.4.1? Thanks!

**Comment by sigma67** [comment]
I have tested with the RTE in a standard Text & Media content element and it seems to work fine - the whitespace is output in the frontend exactly as expected, while in the seminars description whitespace is not stored in the database field.

What's interesting to me is that the whitespace fields are still being shown in the backend RTE of the event. Just in the tx_seminars_seminars table the 'description' field has the HTML with whitespace removed. Unfortunately I don't know where the extension configures the RTE, but maybe this helps?

An upgrade to v1.4.1 did not help.

**Comment by oliverklee** [comment]
@sigma67 Are you using an RTE?
