### ISSUE TITLE
attendancesPID empty warning even if its set in the organizers

### ISSUE THREAD

**Issue by frereit** [oliverklee/ext-seminars#433]
#### Issue description

In the list view the warning "The TS setup variable plugin.tx_seminars.attendancesPID is empty, but needs to be non-empty. " even when the attendancesPID is set in the organizer for each event.

#### Steps to reproduce the issue

1. Create a new organizer and set a SysFolder to save the records to (in Flexforms)
2. Create one or more events with that organizer
3. Create a list view for these events
4. do NOT set plugin.tx_seminars.attendancesPID in typoscript
5. Observe that a warning is displayed in the Frontend: "The TS setup variable plugin.tx_seminars.attendancesPID is empty, but needs to be non-empty." 

#### What's the expected result?

The warning shouldn't be displayed as all events do have proper sysfolders set through their organizers. Unlike the warning suggests, when registering for these events the registration records are not dumped in the root page but are saved properly in the specified sysfolder. 

#### What's the actual result?

The warning is displayed

#### Additional details / screenshot

- ![The displayed Warning](https://user-images.githubusercontent.com/18506129/71261785-8e443280-233e-11ea-8326-f8fd96d2acd2.png)
)
- ![The Sysfolder is set](https://user-images.githubusercontent.com/18506129/71261811-97350400-233e-11ea-929e-e2eca8d1b614.png)

**Comment by oliverklee** [comment]
This is by design. The PID set in attendancesPID serves as a fallback for organizers that do not have a PID for the registrations set.

(If you'd like to create a PR so that the configuration check goes through all organizers for this and only checks attendancesPID if at least one organizer does not have a PID set, that would be welcome, too.)

**Comment by frereit** [comment]
I will look into doing that, I will first have to familiarize myself with the source code for this. In the meantime, is there a way to disable this warning?

**Comment by oliverklee** [comment]
There is no way to disable individual configuration check warnings. You disable and enable all warnings for an extension in the EM, though.
