### ISSUE TITLE
Convert the new hooks to the new model classes

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#457]
@mk-mxp Would you be willing to convert your new hooks to the new model classes (where is is possible, i.e., where we are not using a bag class)? This would make the hooks more future-proof.

**Comment by mk-mxp** [comment]
I had some cases, where I could not use the new models. IIRC it was when it came to using `Topic`s as the top structure, not `Event`s. I need to look into the hook implementation I did some time ago and see if I can reconstruct the problems I had back then.

**Comment by oliverklee** [comment]
Great, thanks!

**Comment by mk-mxp** [comment]
None of the problems was related to the hooks directly. So, no excuses found.

`BackendRegistrationListView::modifyListRow()` is the only hook having an old model so far, I will convert that the next days. TCE validation in #443 is not finished, yet.
