### ISSUE TITLE
Warning in Thunderbird Lightning about the ICS file in the thank-you email

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#534]
Zeitzonenfehler:

Vergleiche Fehlerkonsole: Für unbekannte Zeitzonen wird die Zeitzone "Lokale Zeit" verwendet.

**Comment by jweiland** [comment]
Das Problem scheint der TZIDPREFIX Parameter / zu sein. Dieser wird immer vorangestellt, dann muss aber auch eine VTIMEZONE definiert sein. 

Siehe auch den Validator unter https://icalendar.org/validator.html#results, der bei folgenden Testdaten einen entsprechenden Fehler liefert:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:TYPO3 CMS
METHOD:PUBLISH
BEGIN:VEVENT
UID:event/362/5ef0848fa638a4.36787455
DTSTAMP:20200622T121439
SUMMARY:Schulung DRS Homepage Baukasten
DESCRIPTION:
DTSTART;TZID=/Europe/Berlin:20200717T090000
DTEND;TZID=/Europe/Berlin:20200717T153000
LOCATION:Gemeindezentrum St. Martin Biberach, Museumstraße 5
ORGANIZER;CN="Diözese Rottenburg Stuttgart":mailto:schulung@baukasten-drs.de
END:VEVENT
END:VCALENDAR



In der folgenden Zeile sollte m.E. der / entfernt werden:

return ';TZID=/' . $timeZone . ':' . strftime('%Y%m%dT%H%M%S', $dateAsUnixTimeStamp);

**Comment by oliverklee** [comment]
Thanks for the analysis!

**Comment by oliverklee** [comment]
The time zones are too complex for now. Let's remove them for version 4.0 and switch to floating date/times instead.
