### ISSUE TITLE
"Starting Point" (plugin.tx_seminars_pi1.pages) has no effect?

### ISSUE THREAD

**Issue by mechanicalman1** [oliverklee/ext-seminars#542]
With seminars 3.1.0 on TYPO3 9.5.16 it looks to me, like plugin.tx_seminars_pi1.pages has no effect.

Seminars List view shows Event type, Place and Organizer in the selector widget from another sysfolder.

```
TypoScript: 
plugin.tx_seminars_pi1 {
  pages = 519
  recursive = 0
}
```

Or alternatively via configuration in Content Element:
![image](https://user-images.githubusercontent.com/59438299/81106641-3df8f600-8f16-11ea-964b-b034fcfb2160.png)

The selector widget still shows data from every sysfolder, no matter where they are in the page tree.

Is this a bug or a feature?

**Comment by oliverklee** [comment]
This is the intended behaviour: The starting point only affects the event records.

**Comment by mechanicalman1** [comment]
Thanks for your fast response!
For me it looks like there's still something wrong:

Records from "disabled" folders are still shown.
Even deleted records (like "event_type") still show an empty option in the selector widget (with no text, but HTML option):
![image](https://user-images.githubusercontent.com/59438299/81211082-2764a480-8fd3-11ea-9b06-3df63f7dbe58.png)
![image](https://user-images.githubusercontent.com/59438299/81211200-51b66200-8fd3-11ea-8e5f-7dd3eb5b18cf.png)

**Comment by mechanicalman1** [comment]
Oliver, now I got it.
The selector widget shows every possible option, whenever there's a seminar related to it, even when they are in the past.
When I delete all seminars it also flushes the selector widget.
There is no reference check for related records.

Now it's ok for me. I can live with it :-)

**Comment by oliverklee** [comment]
> Records from "disabled" folders are still shown.
Even deleted records (like "event_type") still show an empty option in the selector widget (with no text, but HTML option)

@mechanicalman1 Is this still an issue? If yes, could you please open a separate ticket for this? (And of course, I'll greatly appreciate a PR.)

**Comment by mechanicalman1** [comment]
> Is this still an issue?

@oliverklee no, I'm can live with it, as I now know the root cause. It's forbidden to delete e. g. a event_type, that is referenced from a still existing seminar. Then a empty record will appear in the selector widget, as the seminar is still referenced to it.

**Comment by oliverklee** [comment]
@mechanicalman1 This still is a bug, and I'd like it to be fixed at some time (even if you can live with it ;-) ). Would you be so kind to create a ticket? Thanks!
