### ISSUE TITLE
Selector widget shows deleted records as a empty record in html

### ISSUE THREAD

**Issue by mechanicalman1** [oliverklee/ext-seminars#543]
Deleted records (like "event_type") are still shows as empty option in the selector widget (with no text, but clickable HTML option), when a seminar record has a reference to it:

![image](https://user-images.githubusercontent.com/59438299/81503173-7ca9fa00-92e2-11ea-958f-ad22203d3c64.png)
![image](https://user-images.githubusercontent.com/59438299/81503176-82074480-92e2-11ea-9516-f769ba291107.png)

There is no reference check for related records before they are deleted, so this can happen easily.

_Originally posted by @mechanicalman1 in https://github.com/oliverklee/ext-seminars/issues/542#issuecomment-624797588_

**Comment by oliverklee** [comment]
@mechanicalman1 Thanks!

**Comment by oliverklee** [comment]
This is too hard to test and fix with the current architecture. Sorry.
