### ISSUE TITLE
Not possible to clear "deadline_registration" in backend once it was set

### ISSUE THREAD

**Issue by mk-mxp** [oliverklee/ext-seminars#548]
When adding a seminar via backend, it is possible to not set `deadline_registration`. Then it is OK to leave it empty on further editing that seminar. Once a `deadline_registration` was set, it is no more possible to remove it (set to empty). It may be related to Typo3 9.5 not allowing to enter "0" for a date, but having a clear icon wiping out the value.

The problem comes up before the TCE value hook is triggered, which then is provided with the old seminar data (with the old `deadline_registration` value set).

![Screenshot_2020-06-14](https://user-images.githubusercontent.com/55182845/84593881-eae85c00-ae4e-11ea-9e89-f7e69aaa241d.png)

**Comment by oliverklee** [comment]
Are you using MySQL in strict mode? (This might be a bug in the TYPO3 core.)

**Comment by oliverklee** [comment]
And could you also please test (without any changes to your MySQL configuration) whether it helps to change the eval for the `deadline_registration` field in the TCA from `datetime` to `datetime,int`?

**Comment by mk-mxp** [comment]
It is a MariaDB 10.4.12, modes are:

```
MariaDB [(none)]> SELECT @@GLOBAL.sql_mode;
STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
Setting `eval` to your suggestion does the trick.

**Comment by oliverklee** [comment]
I have reported a bug for the Core: https://forge.typo3.org/issues/91731
