### ISSUE TITLE
Registration form not completely translated

### ISSUE THREAD

**Issue by mk-mxp** [oliverklee/ext-seminars#550]
There is no translation file missing, but still the registration form is not translated completely. No matter which language I select, the form fields stay in default language. Other markers and labels are translated as expected.
![Screenshot_2020-06-26](https://user-images.githubusercontent.com/55182845/85890016-d613ad00-b7ec-11ea-96f2-8fff5853fa4b.png)

I have setup an extra site for testing that, with Introduction package as a base. There is no TypoScript but the setting of PIDs for seminars to work and the required extension includes, all extensions not required are deactivated. Still I get partial translated output.

**Comment by oliverklee** [comment]
Does it help if you fully configure your language using TypoScript like this?
https://github.com/oliverklee/typo3-devsite/blob/master/Configuration/TypoScript/languages.typoscript (the first language is German in that configuration.)

**Comment by mk-mxp** [comment]
It helps in the sense of: now the form fields are always German, even in the English version :smile: `config.language` is the TS required to select the language for the form fields.

I hope it does not have negative side effects when I use that as a workaround now...

**Comment by oliverklee** [comment]
@mk-mxp Are you using the complete conditions from my example for the two languages? With that, English should have no German.

**Comment by mk-mxp** [comment]
In my Typo3 V9.5.19, freshly installed with composer, there is no `L` parameter anymore. So Your conditions never match, and I always have `config.language = de`. I do use the new Symfony ExpressionLanguage to do what's necessary:

```
config.language = de
[siteLanguage("twoLetterIsoCode") == "en"]
config.language = en
[END]
#more languages here
```

I'd love to do `config.language = context:language:isoCode`, but that does not exist (numeric `id` only).

**Comment by oliverklee** [comment]
Fixed with the rewritten registration form (and will not be fixed in the legacy registration form). Closing.
