### ISSUE TITLE
What is the best way to delete old registrations/users with references to events?

### ISSUE THREAD

**Issue by dbfischer** [oliverklee/ext-seminars#552]
Because of the GDPR or just to clear out the database I want to delete registrations and fe-users (onetimeaccount) which are older than one year. If I want to delete a registration I get the hint, that there is still a reference to the event.
One way is to delete it by the events list in BE, but this is really inconvenient to delete them one after another.

If I delete several registrations and (one-time)users in List-mode and ignore the references to still existing events ...
is it sufficient to refresh the reference index? Or is this a bad way?

**Comment by oliverklee** [comment]
Please do not use the issue tracker for support questions.
