### ISSUE TITLE
Wochentag des Kursbeginns in Listenübersicht

### ISSUE THREAD

**Issue by thomasvollmann** [oliverklee/ext-seminars#589]
Es liegt vermutlich daran, dass ich zu blind bin.

Wo kann ich einstellen, dass in der Listenübersicht in einer Spalte der Wochentag des ersten Kurstages (Kursbeginn) angezeigt wird?

Version 3.2

**Comment by oliverklee** [comment]
Hi Thomas, please do not use the issue tracker for support questions. Instead, the issue tracker is for tracking issues and feature plans. Also, please write in English as not everybody using the extension understands German.

Also, I do not offer free personal support. If you would like paid support for the extension, please drop me an email.
