### ISSUE TITLE
Stop using createRecursivePageList

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#597]
Replace `DatabaseService::createRecursivePageList` (or `Database::createRecursivePageList`) with calls to the new `PageRepository::findWithinParentPages`.

We need to take into account that the old method works on strings while the new method works on arrays of integers. So we might need the occasional `GeneralUtility::intExplode` or `implode` call.

Depends on #579.

**Comment by Konafets** [comment]
I do not found any occurrence of those methods in ext:seminars. For me this issue can be closed.

**Comment by oliverklee** [comment]
We do not have this anymore indeed. Closing.
