### ISSUE TITLE
Switch emailing in the EmailService from oelib mail functions to the Core SwiftMailer

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-seminars#613]

**Comment by Konafets** [comment]
To have a smaller step, I would migrate `OliverKlee\Oelib\Email\Attachment` to ` Swift_Attachment` in ext:oelib. We can then migrate this in ext:seminar as well. 

What do you think?

**Comment by oliverklee** [comment]
Sounds good (as long as we do this without breaking changes). Then we can do this for oelib 3.3, release that version quickly, and depend on it in seminars.
