### ISSUE TITLE
Bug: PHP Fatal error with seminars 3.3.0 and oelib > 3.1.x

### ISSUE THREAD

**Issue by mk-mxp** [oliverklee/ext-seminars#679]
I get this error:

`PHP Fatal error:  Declaration of Tx_Seminars_FrontEnd_DefaultController::isInitialized() must be compatible with OliverKlee\Oelib\Templating\TemplateHelper::isInitialized(): bool in public/typo3conf/ext/seminars/Classes/FrontEnd/DefaultController.php on line 20`

caused by changes in oelib 3.2.0, being allowed in seminars 3.3.0 as `"oliverklee/oelib": "^3.1.0"`.

Greetings from dependency hell.

**Comment by oliverklee** [comment]
Oh, I looked in the wrong class. Please ignore my comment. On it.

**Comment by oliverklee** [comment]
I've just released oelib 3.2.1 and seminars 3.3.1 which both fix this problem. (Updating either extension will help.) Thanks for reporting this, @mk-mxp!

**Comment by mk-mxp** [comment]
Thanks a lot!
