### ISSUE TITLE
Cannot save dates for a new single event

### ISSUE THREAD

**Issue by webdev2027** [oliverklee/ext-seminars#731]
Hi Oli.

I'm using an single event (Einzel-Veranstaltung). Include Start- and End-Time, clicking Save - after that the fields are empty again. It's not possible to save the dates.

My workaround: Choose instead of "single event" (Einzel-Veranstaltung) -> "event" (Termin), include the Times, clicking save and it works. After that, change the type of event back zu "single event". It works for me, but it's hard to explain that to all editors ...  Something must be wrong?!

TYPO3 8.7.32, seminars 3.2.0, mk-forms 9.5.2, oelib 3.2.1

p.s. had the same at "Anmelde-Deadline" for some weeks ago. There was an date inside, i clear the field, save and the date was back in the input field. But not in database, just in the TCA?!?! I've ignore it .. but maybe the same mistake?

Thanks.
Stefan

![Bildschirmfoto 2021-02-26 um 08 47 36](https://user-images.githubusercontent.com/5501876/109271805-4eb18a00-7810-11eb-9be7-3f0b7020e76c.png)
![Bildschirmfoto 2021-02-26 um 08 47 22](https://user-images.githubusercontent.com/5501876/109271809-4f4a2080-7810-11eb-8696-5e16bc80041a.png)

**Comment by oliverklee** [comment]
Hi @webdev2027, thanks for the bug report.

Let's check a few things:
- Do you get any error messages?
- Does the event have a title?
- Does the event have an organizer?
- Are you using MySQL?
- Which mode(s) is MySQL running in? (Some things probably will not work correctly in strict mode.)

**Comment by webdev2027** [comment]
Hi Oli.
Let's check a few things:

    Do you get any error messages? - **NO**
    Does the event have a title? - **YES, of course** ;)
    Does the event have an organizer? - **YES**
    Are you using MySQL? - **YES, MySQL 5.5.5**, server Microsoft-IIS/8.5
    Which mode(s) is MySQL running in? (Some things probably will not work correctly in strict mode.) - **no strict mode**

* The Events were added a few weeks ago. In this week I add new single events and update older events (change dates etc.) to see this bug. Anyway .. I can live with the workaround and hope, that everything's fine after TYPO3 Update v9.

**Comment by peerlight** [comment]
same problem here

any further questions to investigate?

**Comment by oliverklee** [comment]
Have you tried the latest seminars 3.3.2? In seminars 3.3.1, we've fixed a bug that end dates where limited to 2020-12-31: https://github.com/oliverklee/ext-seminars/issues/677

**Comment by peerlight** [comment]
did not try 3.3.2 because it requires oelib >= 3.2.0 which caused errors

updated 3.3.0 -> 3.3.1 which seems to fix this issue

**Comment by webdev2027** [comment]
Hi, theres no `update` availible in extension manager, that's why I still use `3.2.0`. I also use oelib `3.2.1`. Now I see, theres 3.3.1 and 3.3.2 availible ...

would you recommend to install seminars `3.3.1` with direct upload? the requirements looks good for me?
https://github.com/oliverklee/ext-seminars/blob/main/ext_emconf.php

**Comment by oliverklee** [comment]
@peerlight Which errors do you see with oelib 3.2.0?

**Comment by oliverklee** [comment]
@webdev2027 seminars 3.3.0, 3.3.1 and 3.3.2 are available in the TER. I have no idea why you do not get them offered as update.

You could try a direct upload, but I recommend to get the update in the EM to work instead.

**Comment by peerlight** [comment]
> @peerlight Which errors do you see with oelib 3.2.0?
some time ago; perhaps https://github.com/oliverklee/ext-seminars/issues/679

**Comment by oliverklee** [comment]
Okay, closing this then is this seems to work now. Please feel free to reopen this (or open a new ticket) if the problem still occurs with the latest versions of seminars and oelib.
