### ISSUE TITLE
Date Picker mistake

### ISSUE THREAD

**Issue by Hogego** [oliverklee/ext-seminars#732]
HI, something strange is happening using the date picker for setting an events time and date.
After saving the time, two hours are added - the date of an existing event can't be changed at all.

Typo3 9 / Seminars 3.2

Some help would be great!
Hoge

**Comment by Hogego** [comment]
Hi Oliver, thanks for answering!

I get this message:

Benötigte Erweiterung "mkforms"
The extension mkforms is installed in version 9.5.2 but needed in version 9.5.4 - 9.5.99 and could not be fetched from TER

any hint where i get this?

Hoge

> Am 04.03.2021 um 17:29 schrieb Oliver Klee <notifications@github.com>:
> 
> s

**Comment by oliverklee** [comment]
Oh no, then we've upped the dependencies too far, breaking the non-Composer installations. :-( I'll release a seminars 3.3.3 soon that reduces the dependency to >= 9.5.2. (9.5.4 currently is available via Composer only.)

**Comment by oliverklee** [comment]
@Hogego I've just released seminars 3.3.3 that should now be installable in non-Composer mode again. Could you please test with that version? Thanks!

**Comment by Hogego** [comment]
yes, works fine. Thanks a lot and happy weekend!
Hoge

**Comment by oliverklee** [comment]
Thanks, I'm glad to read that. Have a nice weekend, too!

Closing.
