### ISSUE TITLE
error "no event uid in url" on detail 

### ISSUE THREAD

**Issue by peerlight** [oliverklee/ext-seminars#746]
This URL brings the error "no event uid in url" `/veranstaltungen/details/2005`

This URL works `/veranstaltungen/details?tx_seminars_pi1%5BshowUid%5D=2005&cHash=e9616dec59f873d5f7f488f6c4586d99`

But URLs with lower UIDs work too `/veranstaltungen/details/2004`

We use TYPO3 9.5.26, seminars 3.3.3 and have a list page `/veranstaltungen` and a detail page `/veranstaltungen/details`

URLs of events are `/veranstaltungen/details/1234` and worked for years now (with lower UID)

There is a roueEnhacer config of type Plugin with routePath: '/{showUid}' and requirement for numbers

Any ideas why the given value is not evaluated  correctly?

**Comment by peerlight** [comment]
Seems that in line 274 of FrontEnd/DefaultController.php `piVars['showUid']` is empty when showUid in URL is between `2005` and `2030`

So URLs with higher UIDs work too / again `/veranstaltungen/details/2031`

**Comment by oliverklee** [comment]
Sorry, I have no idea why exactly this happens.

As this happens with the pretty URL only, I guess the problem is with the route enhancer, not in the extension.
