### ISSUE TITLE
TYPO3 10 support

### ISSUE THREAD

**Issue by luberti** [oliverklee/ext-seminars#751]
Hello, I see from the home page that TYPO3 v10 is not yet supported, but looking at the crowdfunding page it looks like the milestone for funding the development od TYPO3 v10 compatibility has been reached, so I would like to know if there is a schedule for realising seminars for TYPO3 v 10.

TIA for your attention and answer

**Comment by oliverklee** [comment]
Hi @luberti, best case: end of 07/2021. Worst case: end of 09/2021.

**Comment by luberti** [comment]
THX Oliver
